import "dotenv/config";
import type { VercelRequest, VercelResponse } from "@vercel/node";
import { Bot, InlineKeyboard, webhookCallback } from "grammy";
import fs from "node:fs";
import path from "node:path";

type Article = { id: string; slug: string; title: string; subtitle?: string; level: string; ieltsTarget?: string; source?: string; originalUrl?: string; description?: string; quizlet?: Record<string, string>; enabled?: boolean; };
type VocabItem = { term: string; definition: string; translation?: string; };
const token = process.env.BOT_TOKEN;
if (!token) throw new Error("BOT_TOKEN is missing");
const bot = new Bot(token);
const ARTICLES_DIR = path.join(process.cwd(), "data", "articles");
const LETTERS = ["A","B","C","D","E","F","G","H","I","J","K"];
const ICONS = ["🅰️","🅱️","🅲","🅳","🅴","🅵","🅶","🅷","🅸","🅹","🅺"];
function escapeHtml(text = "") { return String(text).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }
function escapeRegExp(text = "") { return String(text).replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); }
async function safeEditOrReply(ctx: any, text: string, options: any = {}) { try { if (ctx.callbackQuery?.message) return await ctx.editMessageText(text, options); } catch {} return ctx.reply(text, options); }
function readJson<T>(filePath: string): T { return JSON.parse(fs.readFileSync(filePath,"utf-8")) as T; }
function readArticle(slug: string): Article | null { const p=path.join(ARTICLES_DIR,slug,"article.json"); return fs.existsSync(p)?readJson<Article>(p):null; }
function getArticles(): Article[] { if(!fs.existsSync(ARTICLES_DIR)) return []; return fs.readdirSync(ARTICLES_DIR,{withFileTypes:true}).filter(x=>x.isDirectory()).map(d=>readArticle(d.name)).filter((x): x is Article=>Boolean(x)).filter(x=>x.enabled!==false); }
function getParagraphs(markdown: string) { return markdown.split(/\n\s*\n/g).map(p=>p.trim()).filter(Boolean).filter(p=>!p.startsWith("#")); }
function splitIntoBalancedParts<T>(items: T[]) { const n=items.length<=6?2:3; const per=Math.ceil(items.length/n); const r:T[][]=[]; for(let i=0;i<items.length;i+=per) r.push(items.slice(i,i+per)); return r; }
function getAllVocabulary(slug: string): VocabItem[] { const dir=path.join(ARTICLES_DIR,slug,"vocabulary"); if(!fs.existsSync(dir)) return []; return fs.readdirSync(dir).filter(f=>f.endsWith(".json")).flatMap(f=>readJson<{items:VocabItem[]}>(path.join(dir,f)).items??[]); }
function boldVocabulary(text: string, vocab: VocabItem[]) { let m=escapeHtml(text); const terms=[...vocab].map(x=>x.term?.trim()).filter(Boolean).sort((a,b)=>b.length-a.length); for(const t of terms){ const re=new RegExp(`\\b(${escapeRegExp(escapeHtml(t))})\\b`,"gi"); m=m.replace(re,"<b>$1</b>"); } return m; }
function formatPassagePart(slug: string, page: number) { const p=path.join(ARTICLES_DIR,slug,"passage.md"); if(!fs.existsSync(p)) return null; const parts=splitIntoBalancedParts(getParagraphs(fs.readFileSync(p,"utf-8"))); const part=parts[page]; if(!part) return null; const vocab=getAllVocabulary(slug); const start=parts.slice(0,page).reduce((s,p)=>s+p.length,0); const body=part.map((par,i)=>{ const idx=start+i; return `${ICONS[idx]??"🔹"} <b>Paragraph ${LETTERS[idx]??idx+1}</b>\n\n${boldVocabulary(par,vocab)}`; }).join("\n\n"); return {text:`📖 <b>Passage Part ${page+1}/${parts.length}</b>\n\n${body}`, total:parts.length}; }
function articleKeyboard(slug:string,a:Article){ const kb=new InlineKeyboard().text("📖 Read Passage",`passage:${slug}:0`).row().text("📚 Vocabulary",`vocab:${slug}`).row().text("✅ Part Quizzes",`quiz-menu:${slug}`).row().text("📝 IELTS Exercises",`exercises:${slug}`).row().text("✍️ Grammar Gap Fill",`grammar:${slug}:0`); if(a.originalUrl) kb.row().url("🔗 Original Article",a.originalUrl); kb.row().text("⬅️ All Articles","articles"); return kb; }
function passageKeyboard(slug:string,page:number,total:number){ const kb=new InlineKeyboard(); const row=[]; if(page>0) row.push(InlineKeyboard.text("⬅️ Prev",`passage:${slug}:${page-1}`)); row.push(InlineKeyboard.text("✅ Quiz",`quiz:${slug}:${page}:0`)); if(page<total-1) row.push(InlineKeyboard.text("Next ➡️",`passage:${slug}:${page+1}`)); kb.row(...row); kb.row().text("📚 Vocabulary",`vocab:${slug}`).text("⬅️ Article",`article:${slug}`); return kb; }

bot.command("start", async ctx=>{ const payload=ctx.match; if(payload?.startsWith("article_")){ const slug=payload.replace("article_",""); const a=readArticle(slug); if(!a) return ctx.reply("Article not found."); return ctx.reply(`📚 <b>${escapeHtml(a.title)}</b>\n\n${escapeHtml(a.description??"")}\n\nLevel: ${escapeHtml(a.level)}\nIELTS Target: ${escapeHtml(a.ieltsTarget??"—")}`,{parse_mode:"HTML",reply_markup:articleKeyboard(slug,a)}); } await ctx.reply("📚 English Through Articles\n\nUse /articles to choose a reading unit."); });
bot.command("articles", async ctx=>{ const kb=new InlineKeyboard(); for(const a of getArticles()) kb.text(`📖 ${a.title}`,`article:${a.slug}`).row(); await ctx.reply("📚 Available Articles",{reply_markup:kb}); });
bot.callbackQuery("articles", async ctx=>{ await ctx.answerCallbackQuery(); const kb=new InlineKeyboard(); for(const a of getArticles()) kb.text(`📖 ${a.title}`,`article:${a.slug}`).row(); await safeEditOrReply(ctx,"📚 Available Articles",{reply_markup:kb}); });
bot.callbackQuery(/^article:(.+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1]; const a=readArticle(slug); if(!a) return safeEditOrReply(ctx,"Article not found."); await safeEditOrReply(ctx,`📚 <b>${escapeHtml(a.title)}</b>\n\n${escapeHtml(a.description??"")}\n\nLevel: ${escapeHtml(a.level)}\nIELTS Target: ${escapeHtml(a.ieltsTarget??"—")}`,{parse_mode:"HTML",reply_markup:articleKeyboard(slug,a)}); });
bot.callbackQuery(/^passage:(.+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], page=Number(ctx.match[2]); const r=formatPassagePart(slug,page); if(!r) return safeEditOrReply(ctx,"Passage not found."); await safeEditOrReply(ctx,r.text,{parse_mode:"HTML",reply_markup:passageKeyboard(slug,page,r.total)}); });
bot.callbackQuery(/^vocab:(.+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1]; const kb=new InlineKeyboard().text("B2",`vocab-set:${slug}:b2:0`).text("C1",`vocab-set:${slug}:c1:0`).row().text("C2",`vocab-set:${slug}:c2:0`).text("Collocations",`vocab-set:${slug}:collocations:0`).row().text("⬅️ Article",`article:${slug}`); await safeEditOrReply(ctx,"📚 Choose vocabulary set:",{reply_markup:kb}); });
bot.callbackQuery(/^vocab-set:(.+):(.+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], set=ctx.match[2], page=Number(ctx.match[3]); const a=readArticle(slug); const fp=path.join(ARTICLES_DIR,slug,"vocabulary",`${set}.json`); if(!fs.existsSync(fp)) return safeEditOrReply(ctx,"Vocabulary set not found."); const data=readJson<{title:string;items:VocabItem[]}>(fp); const pages=splitIntoBalancedParts(data.items); const cur=pages[page]??pages[0]; const text=`📚 <b>${escapeHtml(data.title)}</b> ${page+1}/${pages.length}\n\n`+cur.map(i=>`• <b>${escapeHtml(i.term)}</b>\n  ${escapeHtml(i.definition)}`).join("\n\n"); const kb=new InlineKeyboard(); const row=[]; if(page>0) row.push(InlineKeyboard.text("⬅️ Prev",`vocab-set:${slug}:${set}:${page-1}`)); if(page<pages.length-1) row.push(InlineKeyboard.text("Next ➡️",`vocab-set:${slug}:${set}:${page+1}`)); if(row.length) kb.row(...row); if(a?.quizlet?.[set]) kb.row().url("🔗 Learn in Quizlet",a.quizlet[set]); kb.row().text("⬅️ Vocabulary",`vocab:${slug}`); await safeEditOrReply(ctx,text,{parse_mode:"HTML",reply_markup:kb}); });
function getQuiz(slug:string,part:number){ const fp=path.join(ARTICLES_DIR,slug,"quizzes",`part-${part+1}.json`); return fs.existsSync(fp)?readJson<any>(fp):null; }
bot.callbackQuery(/^quiz-menu:(.+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], dir=path.join(ARTICLES_DIR,slug,"quizzes"); const kb=new InlineKeyboard(); if(fs.existsSync(dir)) fs.readdirSync(dir).filter(f=>f.endsWith(".json")).forEach((_,i)=>kb.text(`✅ Part ${i+1} Quiz`,`quiz:${slug}:${i}:0`).row()); kb.text("⬅️ Article",`article:${slug}`); await safeEditOrReply(ctx,"✅ Choose quiz:",{reply_markup:kb}); });
bot.callbackQuery(/^quiz:(.+):(\d+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], part=Number(ctx.match[2]), qIndex=Number(ctx.match[3]); const quiz=getQuiz(slug,part); const q=quiz?.questions[qIndex]; if(!quiz) return safeEditOrReply(ctx,"Quiz not found."); if(!q) return safeEditOrReply(ctx,"🏁 <b>Quiz finished!</b>\n\nGreat work.",{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("📖 Passage",`passage:${slug}:${part}`).row().text("⬅️ Article",`article:${slug}`)}); const kb=new InlineKeyboard(); q.options.forEach((o:string,i:number)=>kb.text(o,`quiz-answer:${slug}:${part}:${qIndex}:${i}`).row()); await safeEditOrReply(ctx,`✅ <b>${escapeHtml(quiz.title)}</b>\n\nQuestion ${qIndex+1}/${quiz.questions.length}\n\n${escapeHtml(q.question)}`,{parse_mode:"HTML",reply_markup:kb}); });
bot.callbackQuery(/^quiz-answer:(.+):(\d+):(\d+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], part=Number(ctx.match[2]), qIndex=Number(ctx.match[3]), selected=Number(ctx.match[4]); const q=getQuiz(slug,part)?.questions[qIndex]; if(!q) return safeEditOrReply(ctx,"Question not found."); const text=selected===q.answer?`✅ <b>Correct!</b>\n\n💡 ${escapeHtml(q.explanation)}`:`❌ <b>Not quite.</b>\n\nCorrect answer: <b>${escapeHtml(q.options[q.answer])}</b>\n\n💡 ${escapeHtml(q.explanation)}`; await safeEditOrReply(ctx,text,{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("➡️ Next",`quiz:${slug}:${part}:${qIndex+1}`).row().text("📖 Passage",`passage:${slug}:${part}`).text("⬅️ Article",`article:${slug}`)}); });
bot.callbackQuery(/^exercises:(.+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], dir=path.join(ARTICLES_DIR,slug,"exercises"); const kb=new InlineKeyboard(); if(fs.existsSync(dir)){ for(const f of fs.readdirSync(dir).filter(f=>f.endsWith(".json")&&f!=="grammar-gap-fill.json")){ const ex=readJson<any>(path.join(dir,f)); kb.text(`📝 ${ex.title}`,`exercise-show:${slug}:${f}`).row(); } } kb.text("⬅️ Article",`article:${slug}`); await safeEditOrReply(ctx,"📝 Choose IELTS exercise:",{reply_markup:kb}); });
bot.callbackQuery(/^exercise-show:(.+):(.+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], file=ctx.match[2]; const fp=path.join(ARTICLES_DIR,slug,"exercises",file); if(!fs.existsSync(fp)) return safeEditOrReply(ctx,"Exercise not found."); const ex=readJson<any>(fp); let text=`📝 <b>${escapeHtml(ex.title)}</b>\n\n${escapeHtml(ex.instructions??"")}\n\n`; for(const q of ex.questions??[]) text+=`${q.number}. ${escapeHtml(q.statement??q.prompt??q.sentence??"")}\n`; await safeEditOrReply(ctx,text,{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("⬅️ Article",`article:${slug}`)}); });
bot.callbackQuery(/^grammar:(.+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], qIndex=Number(ctx.match[2]); const ex=readJson<any>(path.join(ARTICLES_DIR,slug,"exercises","grammar-gap-fill.json")); const q=ex.questions[qIndex]; if(!q) return safeEditOrReply(ctx,"🏁 <b>Grammar exercise finished!</b>",{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("⬅️ Article",`article:${slug}`)}); await safeEditOrReply(ctx,`✍️ <b>${escapeHtml(ex.title)}</b>\n\nQuestion ${qIndex+1}/${ex.questions.length}\n\n${escapeHtml(q.sentence)}\n\nWrite ${q.minWords}-${q.maxWords} words.`,{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("👁 Show Answer",`grammar-answer:${slug}:${qIndex}`).row().text("➡️ Next",`grammar:${slug}:${qIndex+1}`).row().text("⬅️ Article",`article:${slug}`)}); });
bot.callbackQuery(/^grammar-answer:(.+):(\d+)$/, async ctx=>{ await ctx.answerCallbackQuery(); const slug=ctx.match[1], qIndex=Number(ctx.match[2]); const q=readJson<any>(path.join(ARTICLES_DIR,slug,"exercises","grammar-gap-fill.json")).questions[qIndex]; await safeEditOrReply(ctx,`✅ <b>Answer:</b> ${escapeHtml(q.answer[0])}\n\n💡 ${escapeHtml(q.explanation??"")}`,{parse_mode:"HTML",reply_markup:new InlineKeyboard().text("➡️ Next",`grammar:${slug}:${qIndex+1}`).row().text("⬅️ Article",`article:${slug}`)}); });
const handleUpdate = webhookCallback(bot, "http");
export default async function handler(req: VercelRequest, res: VercelResponse) { if(req.method==="GET") return res.status(200).send("Telegram bot webhook is running."); if(req.method!=="POST") return res.status(405).send("Method Not Allowed"); return handleUpdate(req,res); }
